// A bunch of tests are generated by the build.rs and placed in the build OUT_DIR.
// If test fails it is easier to copy the test as a unit test and debug thereafter.
include!(concat!(env!("OUT_DIR"), "/generated_tests.rs"));
